# Build Stage
FROM node:17.1-alpine as build-stage
WORKDIR /app
COPY MoneyMinter/package*.json ./
RUN npm install
COPY MoneyMinter ./
RUN npm run build

# Production Stage
FROM nginx:1.22.1-alpine as prod-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]