# Stage 1: Build the application
FROM node:17.1-alpine AS build-stage

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json (if exists) from the frontend folder
COPY MoneyMinter/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend application code
COPY MoneyMinter/ ./

# Build the application
RUN npm run build

# Stage 2: Serve the application with Nginx
FROM nginx:1.22.1-alpine AS prod-stage

# Copy the build output to Nginx's HTML directory
COPY --from=build-stage /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
