name: Deploy backend

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH_KEY" > keyfile
        chmod 600 keyfile

    - name: Set up known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ec2-13-200-235-248.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts

    - name: SSH and deploy
      run: |
        ssh -t -i keyfile ubuntu@ec2-13-200-235-248.ap-south-1.compute.amazonaws.com "sudo bash ~/deploy.sh"
