name: Deploy backend

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH_KEY" > keyfile
        chmod 600 keyfile
        ssh -t -i keyfile ubuntu@ec2-13-200-235-248.ap-south-1.compute.amazonaws.com "sudo bash ~/deploy.sh"
